---
- name: Install nginx
  apt:
    name: nginx
    state: present
- name: Configure nginx
  copy:
    content: "Hello from {{ inventory_hostname }}!"
    dest: /var/www/html/index.html
- name: Restart nginx
  service:
    name: nginx
    state: restarted

