---
- name: Install nginx
  apt:
    name: nginx
    state: present
- name: Configure nginx proxy
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/sites-available/default
- name: Restart nginx
  service:
    name: nginx
    state: restarted

